### ISSUE TITLE
Pressing "a" in Dialogue Graph changes window

### ISSUE THREAD

**Issue by cwule** [Brainshack/unity-tutorials#1]
I really like the tutorial as it breaks down how to actually use xnode with your own dialogue. 
However, I have a very weird error. 
When I open the dialogue graph in your example scene and want to edit the dialogue segment, typing the letter"a" switches between the dialogue graph and the Unity Player windows. All other letters type as expected.
I thought this might be some new Unity shortcut of Unity 2020.x, but trying it e.g. with the xnode/example project didn't show this behavior???

**Comment by Brainshack** [comment]
AFAIK this is a bug in xnode that in the mean time has been fixed.

Haven't looked at it for a while but I posted an issue on their github
which has been resolved by now.

Would have to try it out myself to be sure.



Am Mi., 24. Feb. 2021 um 20:10 Uhr schrieb cwule <notifications@github.com>:

**Comment by Brainshack** [comment]
Here is the original issue. 

It was the same button but different behaviour but i suspect it to have the same cause.

https://github.com/Siccity/xNode/issues/299#issuecomment-765028032

**Comment by cwule** [comment]
Thanks for the superquick reply, found your comment in the xnode repo!
